name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install PyQt6 Pillow pyinstaller
    - run: pyinstaller --onefile --windowed main.py
    - uses: actions/upload-artifact@v3
      with:
        name: TIMage-exe
        path: dist/main.exe